name: Generate Base Snapshot
on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run sandbox:snapshot-base
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: team_mka3yuagnBml8NSLbVUckQta
          VERCEL_PROJECT_ID: prj_adf9dVr1udI8tMjMufzIvHsPe5aC
